image: alpine/edge
packages:
- rsync
- coreutils
- multimarkdown
sources:
- https://git.sr.ht/~bt/barf
secrets:
- 07201d32-1451-4a8f-9bff-ce8b2232c67d
tasks:
- build: |
    cd barf
    sudo make build
- deploy-blog: |
    cd barf
    rsync --rsh="ssh -o StrictHostKeyChecking=no -i ~/.ssh/07201d32-1451-4a8f-9bff-ce8b2232c67d" -rzP build/ bt@barf.btxx.org:/var/www/barf