image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- cmake
- git
- rsync
- coreutils
- hut
environment:
  repo: barf
  site: barf.btxx.org
tasks:
- build-multimarkdown: |
    git clone https://github.com/fletcher/MultiMarkdown-6.git
    cd MultiMarkdown-6
    sudo cmake . -DCMAKE_BUILD_TYPE=Release
    sudo make
    sudo make install
    cd ..
- build-barf: |
    cd $repo
    mkdir build
    make build
- package: |
    cd $repo/build
    tar -cvzh . > ../site.tar.gz
- deploy: |
    hut pages publish -d $site $repo/site.tar.gz
